const express = require('express')
const bodyParser = require('body-parser')
const rootRoute = require('./routes/rootRoute')
const addBookStores = require('./routes/bookStores/addBookStores')
const getBookStores = require('./routes/bookStores/getBookStores')
const editBookStores = require('./routes/bookStores/editBookStores')
const deleteBookStores = require('./routes/bookStores/deleteBookStore')
const addLibrary = require('./routes/library/addLibrary')
const getLibrary = require('./routes/library/getLibrary')
const editLibrary = require('./routes/library/editLibrary')
const deleteLibrary = require('./routes/library/deleteLibrary')
const addBooks = require('./routes/books/addBooks')
const getBooks = require('./routes/books/getBooks')
const editBooks = require('./routes/books/editBooks')
const deleteBooks = require('./routes/books/deleteBooks')
const addUsers = require('./routes/register/users/registerUsers')
const getUsers = require('./routes/register/users/getUsers')
const editUsers = require('./routes/register/users/editUsers')
const deleteUsers = require('./routes/register/users/deleteUsers')
const addAdmin = require('./routes/admin/addAdmin')
const getAdmin = require('./routes/admin/getAdmin')
const editAdmin = require('./routes/admin/editAdmin')
const deleteAdmin = require('./routes/admin/deleteAdmin')
const addCustomer = require('./routes/customer/addCustomer')
const getCustomer = require('./routes/customer/getCustomer')
const editCustomer = require('./routes/customer/editCustomer')
const deleteCustomer = require('./routes/customer/deleteCustomer')
const addTransactions = require('./routes/transactions/addTransactions')
const getTransactions = require('./routes/transactions/getTransactions')
const editTransactions = require('./routes/transactions/editTransactions')
const deleteTransactions = require('./routes/transactions/deleteTransactions')
const loginRoutes = require('./routes/loginRoutes')

const app = express()
app.use(rootRoute)

app.use(bodyParser.json())
app.use(loginRoutes)
app.use(getBookStores)
app.use(addBookStores)
app.use(editBookStores)
app.use(deleteBookStores)
app.use(addLibrary)
app.use(getLibrary)
app.use(editLibrary)
app.use(deleteLibrary)
app.use(addBooks)
app.use(getBooks)
app.use(editBooks)
app.use(deleteBooks)
app.use(addUsers)
app.use(getUsers)
app.use(editUsers)
app.use(deleteUsers)
app.use(addAdmin)
app.use(getAdmin)
app.use(editAdmin)
app.use(deleteAdmin)
app.use(addCustomer)
app.use(getCustomer)
app.use(editCustomer)
app.use(deleteCustomer)
app.use(addTransactions)
app.use(getTransactions)
app.use(editTransactions)
app.use(deleteTransactions)

const port = 3000
app.listen(port, () => {
  console.log(`Backend app is running in http://localhost:${port}`);
})
